# Generated by Django 3.2.7 on 2021-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('rated', models.CharField(blank=True, max_length=20, null=True)),
                ('released', models.DateField()),
                ('runtime', models.IntegerField(null=True)),
                ('writer', models.CharField(max_length=500)),
                ('plot', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('poster_url', models.CharField(max_length=200)),
                ('type_field', models.CharField(db_column='type_', max_length=12, null=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
