# Generated by Django 5.0.4 on 2024-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20211002_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type_field",
            field=models.CharField(
                db_column="type_", default="movie", max_length=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="source",
            field=models.CharField(
                choices=[
                    ("imdb", "IMDB"),
                    ("rotten_toms", "ROTTEN_TOMATOES"),
                    ("metacritic", "METACRITIC"),
                ],
                max_length=50,
            ),
        ),
    ]
