# Generated by Django 3.2.7 on 2021-09-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avg_rating',
        ),
    ]
