# Generated by Django 3.2.7 on 2021-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default=None, max_length=60, unique=True, verbose_name="email"
            ),
        ),
    ]
