version: "3.8"

services:
  djangogunicorn:
    build:
      context: ./app
      dockerfile: Dockerfile.inst.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles
    expose:
      - "8000"
    env_file:
      - ./app/.env.staging
    # network_mode: bridge

  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - djangogunicorn
    # network_mode: bridge

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    env_file:
      - ./nginx/.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    # network_mode: bridge

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
# networks:
#   default:
#     external:
#       name: nginx-proxy
