version: "3.8"

services:
  movies:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - DJANGO_SETTINGS_MODULE=config.settings.local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev

volumes:
  postgres_data:
