[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["mattyocode"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "3.2.7"
djangorestframework = "3.12.4"
psycopg2-binary = "2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
