FROM nginx:1.19-alpine

# RUN mkdir log

COPY ./default.conf /etc/nginx/conf.d/default.conf

# COPY ./nginx.conf /etc/nginx/templates/nginx.conf.template

# COPY ./start.sh ./

# RUN chmod 755 ./start.sh

# CMD ["./start.sh"]